/**
 *
 * $Id$
 */
package supplychain.validation;

import java.util.Date;

import supplychain.ShipmentOrder;

/**
 * A sample validator interface for {@link supplychain.DeliveryConfirmation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeliveryConfirmationValidator {
	boolean validate();

	boolean validateConfirmationId(String value);
	boolean validateDeliveryDate(Date value);
	boolean validateRequiresShipment(ShipmentOrder value);
}
