/**
 *
 * $Id$
 */
package supplychain.validation;

import supplychain.ProductOrder;

/**
 * A sample validator interface for {@link supplychain.Invoice}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InvoiceValidator {
	boolean validate();

	boolean validateProductType(String value);
	boolean validateShipmentOrder(String value);
	boolean validateInvoiceId(String value);
	boolean validateTotalAmount(double value);
	boolean validateInProductOrder(ProductOrder value);
}
