/**
 *
 * $Id$
 */
package supplychain.validation;

import java.util.Date;

/**
 * A sample validator interface for {@link supplychain.IoTDataStreams}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IoTDataStreamsValidator {
	boolean validate();

	boolean validateStreamId(String value);
	boolean validateData(String value);
	boolean validateTimestamp(Date value);
}
