/**
 *
 * $Id$
 */
package supplychain.validation;


/**
 * A sample validator interface for {@link supplychain.IoTSensors}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IoTSensorsValidator {
	boolean validate();

	boolean validateSensorId(String value);
	boolean validateSensorType(String value);
	boolean validateLocation(String value);
	boolean validateReading(double value);
}
