/**
 *
 * $Id$
 */
package supplychain.validation;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link supplychain.Offer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OfferValidator {
	boolean validate();

	boolean validateType(String value);
	boolean validatePrice(double value);
	boolean validateQuantity(double value);
	boolean validateOfferId(BigInteger value);
}
