/**
 *
 * $Id$
 */
package supplychain.validation;

import supplychain.Invoice;

/**
 * A sample validator interface for {@link supplychain.PaymentSettlementsConditions}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PaymentSettlementsConditionsValidator {
	boolean validate();

	boolean validateType(String value);
	boolean validateConditions(String value);
	boolean validatePaymentConditions(String value);
	boolean validateTriggersPayment(Invoice value);
}
