/**
 *
 * $Id$
 */
package supplychain.validation;

import java.math.BigInteger;

import java.util.Date;

import supplychain.Offer;
import supplychain.ProductList;

/**
 * A sample validator interface for {@link supplychain.ProductOrder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProductOrderValidator {
	boolean validate();

	boolean validateType(String value);
	boolean validateOrderId(String value);
	boolean validateQuantity(BigInteger value);
	boolean validateOrderDate(Date value);
	boolean validateOrderProductList(ProductList value);
	boolean validateCreatedFrom(Offer value);
}
