/**
 *
 * $Id$
 */
package supplychain.validation;

import supplychain.CO2;
import supplychain.Invoice;
import supplychain.IoTDataStreams;
import supplychain.ProductOrder;
import supplychain.ProductOrigin;
import supplychain.SupplierCertificates;

/**
 * A sample validator interface for {@link supplychain.ShipmentOrder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ShipmentOrderValidator {
	boolean validate();

	boolean validateType(String value);
	boolean validateTime_interval(String value);
	boolean validateShipmentId(int value);
	boolean validateStatus(String value);
	boolean validateProductOrder(ProductOrder value);
	boolean validateInvoice(Invoice value);
	boolean validateEmissions(CO2 value);
	boolean validateCertificate(SupplierCertificates value);
	boolean validateOrigin(ProductOrigin value);
	boolean validateIotData(IoTDataStreams value);
}
